// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TaskMeta.Shared.Models;

public partial class aspnetAllowance_Blazorba503dd58dc0418c97827d9976eb9f08Context : DbContext
{
    public aspnetAllowance_Blazorba503dd58dc0418c97827d9976eb9f08Context(DbContextOptions<aspnetAllowance_Blazorba503dd58dc0418c97827d9976eb9f08Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Job> Jobs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Job>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Jobs");

            entity.Property(e => e.DateAssigned).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}