// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TaskMeta.Data.Models;

public partial class TaskWeek
{
    [Key]
    public int Id { get; set; }

    public DateOnly WeekStartDate { get; set; }

    public int StatusId { get; set; }

    [Column(TypeName = "money")]
    public decimal Value { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [InverseProperty("TaskWeek")]
    public virtual ICollection<TaskActivity> TaskActivities { get; set; } = new List<TaskActivity>();
}