// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TaskMeta.Data.Models;

public partial class TaskDefinition
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [Column(TypeName = "money")]
    public decimal Value { get; set; }

    public int Sequence { get; set; }

    public bool? Active { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }
}