// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TaskMeta.Shared.Models;

public partial class Job
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Description { get; set; }

    public DateOnly DateAssigned { get; set; }

    public DateOnly DateDue { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [Column(TypeName = "money")]
    public decimal Value { get; set; }

    public bool Complete { get; set; }

    [NotMapped]
    public string ValueString
    {
        get
        {
            return Value.ToString("0.00"); // Format the value with 2 decimal places
        }
        set
        {

            decimal v = 0;
            if (decimal.TryParse(value, out v))
            {
                Value = v;
            }

        }
    }

    [NotMapped]
    public DateTime? DateTimeDue
    {
        get
        {
            return DateDue!.ToDateTime(TimeOnly.FromDateTime(DateTime.MinValue));
        }
        set
        {
            DateDue = DateOnly.FromDateTime(value.Value);
        }
    }


    [ForeignKey("UserId")]
    [InverseProperty("JobUsers")]
    public virtual ApplicationUser User { get; set; }
}