// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskMeta.Shared.Models;

public partial class TaskWeek
{
    [Key]
    public int Id { get; set; }

    public DateOnly WeekStartDate { get; set; }

    public int StatusId { get; set; }

    [Column(TypeName = "money")]
    public decimal Value { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [InverseProperty("TaskWeek")]
    public virtual ICollection<TaskActivity> TaskActivityList { get; set; } = new List<TaskActivity>();

    [ForeignKey("UserId")]
    [InverseProperty("UserTaskWeeks")]
    public virtual ApplicationUser User { get; set; }
}