// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskMeta.Shared.Models;

public partial class TaskDefinition
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [Column(TypeName = "money")]
    public decimal Value { get; set; }

    public int Sequence { get; set; }

    public bool? Active { get; set; }


    [StringLength(450)]
    public string UserId { get; set; }


    [ForeignKey("UserId")]
    [InverseProperty("TaskDefinitionUsers")]
    public virtual ApplicationUser User { get; set; }
    [NotMapped]
    public string ValueString
    {
        get
        {
            return Value.ToString("0.00"); // Format the value with 2 decimal places
        }
        set
        {
            
            decimal v = 0;
            if (decimal.TryParse(value, out v))
            {
                Value = v;
            }

        }
    }
}
